# Generated by Django 5.2.8 on 2025-12-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_address_order_city_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
