# Generated by Django 5.2.8 on 2025-12-17 15:50

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_receipt_digest_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=store.models.order_receipt_upload_to),
        ),
    ]
