# Generated by Django 5.2.8 on 2025-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_receipt_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'شماره\u200cگذار پیش\u200cفاکتور دستی',
                'verbose_name_plural': 'شماره\u200cگذار پیش\u200cفاکتور دستی',
            },
        ),
    ]
