# Generated by Django 5.0.7 on 2025-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_is_other',
            field=models.BooleanField(default=False),
        ),
    ]
