# Generated by Django 5.0.7 on 2025-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال (تومان)')),
                ('free_shipping_min_total', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ برای ارسال رایگان (تومان)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات ارسال',
                'verbose_name_plural': 'تنظیمات ارسال',
            },
        ),
    ]
