# Generated by Django 5.0.7 on 2025-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discountcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=32, verbose_name='شماره کارت')),
                ('card_holder', models.CharField(blank=True, max_length=120, verbose_name='نام صاحب کارت')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='آیدی تلگرام (بدون @)')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='شماره واتساپ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات پرداخت',
                'verbose_name_plural': 'تنظیمات پرداخت',
            },
        ),
    ]
