# Generated by Django 5.2.8 on 2025-12-20 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_chatthread_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_discount_codes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر اختصاصی'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دفعات استفاده'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دفعات استفاده برای هر کاربر'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, verbose_name='دفعات استفاده'),
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(verbose_name='شناسه سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='core.discountcode', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از کد تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای کد تخفیف',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('discount_code', 'order_id'), name='uniq_discount_code_order')],
            },
        ),
    ]
