# Generated by Django 5.2.8 on 2025-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_discountcode_assigned_user_discountcode_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='source_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='کد مبدا'),
        ),
    ]
