# Generated by Django 5.0.7 on 2025-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactmessage_phone_contactmessage_replied_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_hits', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily visit stat',
                'verbose_name_plural': 'Daily visit stats',
            },
        ),
    ]
