# Generated by Django 5.0.7 on 2025-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_dailyvisitstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل سایت'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='وبسایت'),
        ),
    ]
