# Generated by Django 5.2.8 on 2025-12-17 00:06

import django.db.models.deletion
import otp_sms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsOTPDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name of this device.', max_length=64)),
                ('confirmed', models.BooleanField(default=True, help_text='Is this device ready for use?')),
                ('phone', models.CharField(db_index=True, max_length=24)),
                ('token_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('token_salt', models.CharField(default=otp_sms.models._new_salt, max_length=64)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_count_window_start', models.DateTimeField(blank=True, null=True)),
                ('send_count_in_window', models.PositiveIntegerField(default=0)),
                ('verify_fail_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(help_text='The user that this device belongs to.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'phone'), name='uniq_sms_otp_device_user_phone')],
            },
        ),
    ]
